### ISSUE TITLE
ignoring Boxfile when specifying python34

### ISSUE THREAD

**Issue by johaywood** [nanobox-io/nanobox-engine-python#5]
I've specified

```
build: 
  runtime: python34
```

in my Boxfile, but nanobox doesn't seem to recognize this and I get a box with python27.

**Comment by tylerflint** [comment]
Oh, it looks like the docs haven't been updated to reflect the changes since the overlay feature. The attribute has been renamed to "python_runtime". That change was introduced to allow engines with the potential to pull in other runtimes, such as nodejs_runtime if bower or some other frontend compiler is needed. 

Thanks!

**Comment by johaywood** [comment]
did a `nanobox update` and updated the Boxfile with the `python_runtime` attribute and now sniff is detecting a nodejs app.

**Comment by tylerflint** [comment]
That was an issue this week that has been resolved with a new docker build image. Try the following:

nanobox reload
nanobox update-images
nanobox dev

**Comment by johaywood** [comment]
:+1: got it. thanks!
